// <auto-generated />
using System;
using CourseSchedulingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseSchedulingSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190406204657_RemoveIdentityFramework")]
    partial class RemoveIdentityFramework
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CreditHours")
                        .HasColumnType("decimal(5, 3)");

                    b.Property<Guid>("DepartmentId");

                    b.Property<bool>("IsGraduate");

                    b.Property<bool>("IsUndergraduate");

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<Guid>("SubjectId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubjectId", "Number")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.CourseAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("CourseAttributes");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.CourseCourseAttribute", b =>
                {
                    b.Property<Guid>("CourseId");

                    b.Property<Guid>("CourseAttributeId");

                    b.HasKey("CourseId", "CourseAttributeId");

                    b.HasIndex("CourseAttributeId");

                    b.ToTable("CourseCourseAttributes");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.CourseScheduleType", b =>
                {
                    b.Property<Guid>("CourseId");

                    b.Property<Guid>("ScheduleTypeId");

                    b.HasKey("CourseId", "ScheduleTypeId");

                    b.HasIndex("ScheduleTypeId");

                    b.ToTable("CourseScheduleTypes");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.DepartmentUser", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("DepartmentId");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentUsers");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.InstructionalMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsRoomRequired");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("InstructionalMethods");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Middle");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BuildingId");

                    b.Property<int>("Capacity");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Number")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "Number")
                        .IsUnique();

                    b.ToTable("Room");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.ScheduleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("ScheduleTypes");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.TermPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid>("TermId");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("TermParts");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsLockedOut");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Course", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourseSchedulingSystem.Data.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.CourseCourseAttribute", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.CourseAttribute", "CourseAttribute")
                        .WithMany("CourseCourseAttributes")
                        .HasForeignKey("CourseAttributeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourseSchedulingSystem.Data.Models.Course", "Course")
                        .WithMany("CourseCourseAttributes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.CourseScheduleType", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.Course", "Course")
                        .WithMany("CourseScheduleTypes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CourseSchedulingSystem.Data.Models.ScheduleType", "ScheduleType")
                        .WithMany("CourseScheduleTypes")
                        .HasForeignKey("ScheduleTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.DepartmentUser", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.Department", "Department")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourseSchedulingSystem.Data.Models.User", "User")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.Room", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CourseSchedulingSystem.Data.Models.TermPart", b =>
                {
                    b.HasOne("CourseSchedulingSystem.Data.Models.Term", "Term")
                        .WithMany("TermParts")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
